Global:
  model_name: PP-OCRv4_mobile_det
  d2s_train_image_shape: [3, 640, 640]
Architecture:
  model_type: det
  algorithm: DB
  Transform: null
  Backbone:
    name: PPLCNetV3
    scale: 0.75
    det: true
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: true
  Head:
    name: DBHead
    k: 50
    fix_nan: true
Metric:
  name: DetMetric
  main_indicator: hmean
